// Auto-generated YARA rules for zero-day threats
// Generated by: Ransomware Defense System (Auto-Generator)
// DO NOT manually edit — rules are managed by yara_generator.py

import "hash"

rule AutoDetection_unknown_crypto_locker_3d44212b
{
    meta:
        description = "Auto-generated rule for zero-day threat caught by behavioral DB"
        author = "Ransomware Defense System (Auto-Generator)"
        date = "2026-02-23"
        original_file = "unknown_crypto_locker.exe"
        process_source = "unknown_crypto_locker.exe"
        hash_md5 = "3d44212bba2d7a88d6c83ce8523bba88"
        hash_sha256 = "15b41a488c356c0e331facdea6c836a6cec021f12d5fde9844e7ca4a1aa0361a"
    condition:
        hash.md5(0, filesize) == "3d44212bba2d7a88d6c83ce8523bba88" or hash.sha256(0, filesize) == "15b41a488c356c0e331facdea6c836a6cec021f12d5fde9844e7ca4a1aa0361a"
}

rule AutoDetection_FileSystem_2d9b2e2a
{
    meta:
        description = "Auto-generated rule for zero-day threat caught by behavioral DB"
        author = "Ransomware Defense System (Auto-Generator)"
        date = "2026-03-01"
        original_file = "ransomware_sim.exe"
        process_source = "FileSystem"
        hash_md5 = "2d9b2e2a9cb7054d9a6ab6f0ac3b13ed"
        hash_sha256 = "dd41e6c133b6eed4c506f1dbba06e91c73c0f71e24c8f8c36c9d1428cdae3b52"
    condition:
        hash.md5(0, filesize) == "2d9b2e2a9cb7054d9a6ab6f0ac3b13ed" or hash.sha256(0, filesize) == "dd41e6c133b6eed4c506f1dbba06e91c73c0f71e24c8f8c36c9d1428cdae3b52"
}


rule AutoDetection_FileSystem_316ea485
{
    meta:
        description = "Auto-generated rule for zero-day threat caught by behavioral DB"
        author = "Ransomware Defense System (Auto-Generator)"
        date = "2026-03-08"
        original_file = "desktop_ransomware_sim.exe"
        process_source = "FileSystem"
        hash_md5 = "316ea48587daca72898304a9c5d4d7e0"
        hash_sha256 = "e522f79b29c77edb017631d07a7c921f3d356f69b058fc79910d542108c9f395"
    condition:
        hash.md5(0, filesize) == "316ea48587daca72898304a9c5d4d7e0" or hash.sha256(0, filesize) == "e522f79b29c77edb017631d07a7c921f3d356f69b058fc79910d542108c9f395"
}


rule AutoDetection_powershell_13cccb79
{
    meta:
        description = "Auto-generated rule for zero-day threat caught by behavioral DB"
        author = "Ransomware Defense System (Auto-Generator)"
        date = "2026-03-08"
        original_file = "powershell.exe"
        process_source = "powershell.exe"
        hash_md5 = "13cccb79aafffb07c94e586b75817486"
        hash_sha256 = "529ee9d30eef7e331b24e66d68205ab4554b6eb3487193d53ed3a840ca7dde5d"
    condition:
        hash.md5(0, filesize) == "13cccb79aafffb07c94e586b75817486" or hash.sha256(0, filesize) == "529ee9d30eef7e331b24e66d68205ab4554b6eb3487193d53ed3a840ca7dde5d"
}

